version: 2
updates:
- package-ecosystem: cargo
  directory: "/foodi-backend"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
  ignore:
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_derive
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: rocket_contrib
    versions:
    - 0.4.6
  - dependency-name: rocket
    versions:
    - 0.4.6
- package-ecosystem: npm
  directory: "/foodi-frontend"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
  ignore:
  - dependency-name: typed-rest-client
    versions:
    - 1.8.1
    - 1.8.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
  - dependency-name: tslib
    versions:
    - 2.1.0
