dist: xenial
branches:
  only:
    - master
matrix:
  fast_finish: true
  allow_failures:
    - rust: stable
    - rust: beta
  include:
    - language: rust
      rust: nightly
      cache: cargo
      script:
        - cd foodi-backend
        - cargo test --verbose --all
    - language: rust
      rust: beta
      cache: cargo
      script:
        - cd foodi-backend
        - cargo test --verbose --all
    - language: rust
      rust: stable
      cache: cargo
      script:
        - cd foodi-backend
        - cargo test --verbose --all
    - language: node_js
      node_js: node
      cache:
        yarn: true
        directories:
          - foodi-frontend/node_modules
      before_script:
        - cd foodi-frontend
        - yarn global add parcel-bundler
        - yarn install
      script:
        - yarn build
