name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: foodi-backend

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v3
      - uses: brndnmtthws/rust-action-rustup@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Check formatting
        run: cargo fmt --all -- --check
